version: "3.5"
services:
  toriel:
    build: .
    container_name: toriel
    depends_on:
      - redis
    volumes:
      - type: bind
        source: /toriel/credentials.json
        target: /app/credentials.json
        read_only: true
      - type: bind
        source: /toriel/data
        target: /app/data
    environment:
      NadekoBot_RedisOptions: redis,name=toriel
      NadekoBot_ShardRunCommand: dotnet
      NadekoBot_ShardRunArguments: NadekoBot.dll {0} {1}
    restart: always
  redis:
    image: redis:alpine
    sysctls:
      net.core.somaxconn: 511
    restart: always
